name: Gradle Build Workflow

on:
  push:
    branches:
      - CI_CD_Github_Actions

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Git repository
      uses: actions/checkout@v3
      with:
        ref: 'CI_CD_Github_Actions'

    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'adopt'

    - name: Cache Gradle packages
      uses: actions/cache@v3
      with:
        path: |
          ~/.gradle/caches
          ~/.gradle/wrapper
        key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*') }}
        restore-keys: |
          ${{ runner.os }}-gradle-

    - name: Grant execute permission for gradlew
      run: chmod +x ./mongo_rest/gradlew

    - name: Run Gradle build
      run: |
        java -version
        cd mongo_rest && ./gradlew :safetraxrest:distZip

    - name: List distributions
      run: ls mongo_rest/safetraxrest/build/distributions
