name: CI/CD Workflow

on:
  push:
    branches: [ "CI_CD_Github_Actions" ]
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: centos-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      with:
        ref: 'CI_CD_Github_Actions'
    
    - name: Set up Java
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        
    - name: Run Gradle build
      run: |
        java -version
        /opt/gradle/gradle-4.4/bin/gradle -version
        cd mongo_rest && /opt/gradle/gradle-4.4/bin/gradle :safetraxrest:distzip
        ls mongo_rest/safetraxrest/build/distributions
        
    - name: Store artifacts in GCP
      run: gsutil cp mongo_rest/safetraxrest/build/distributions/safetraxrest.zip gs://test-live-deploy/SERVERV2
      env:
        GCP_SA_KEY: ${{ secrets.GCP_SA_KEY }}
        
    - name: Deploy to another server in GCP
      run: ssh -i ${{ secrets.SSH_PRIVATE_KEY_PATH }} venu@cicd-test -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no "sudo /home/venu/ETS-mongoser-deployment-updated.sh"
      env:
        SSH_PRIVATE_KEY_PATH: /tmp/ssh_key
      shell: bash
