name: CI/CD Workflow

on:
  push:
    branches: [ "CI_CD_Github_Actions" ]
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: centos-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      with:
        ref: 'CI_CD_Github_Actions'
    
    - name: Set up Java
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        
    - name: Run Gradle build
      run: |
        java -version
        /opt/gradle/gradle-4.4/bin/gradle -version
        cd mongo_rest && /opt/gradle/gradle-4.4/bin/gradle :safetraxrest:distzip
        ls mongo_rest/safetraxrest/build/distributions
        
   
